//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMO_DBEntities : DbContext
    {
        public HMO_DBEntities()
            : base("name=HMO_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<HMO> HMOes { get; set; }
        public virtual DbSet<KingOfDosage> KingOfDosages { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<MedicinesToClient> MedicinesToClients { get; set; }
        public virtual DbSet<TimeToMedicinesForClient> TimeToMedicinesForClients { get; set; }
    }
}
