//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinesToClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicinesToClient()
        {
            this.TimeToMedicinesForClients = new HashSet<TimeToMedicinesForClient>();
        }
    
        public long Id { get; set; }
        public long medicinesId { get; set; }
        public long clientId { get; set; }
        public int Dosage { get; set; }
        public long kindOfDosage { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual KingOfDosage KingOfDosage { get; set; }
        public virtual Medicine Medicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeToMedicinesForClient> TimeToMedicinesForClients { get; set; }
    }
}
