//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.HMO_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeToMedicinesForClient
    {
        public int Id { get; set; }
        public long idMedicineToClient { get; set; }
        public int timeCode { get; set; }
    
        public virtual MedicinesToClient MedicinesToClient { get; set; }
    }
}
